---
- name: Ensure directories of configuration files exist
  ansible.builtin.file:
    path: "{{ item.path | expanduser | dirname }}"
    state: directory
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
  loop: "{{ packages_config_files }}"
  loop_control:
    label: "{{ item.path | dirname }}"

- name: Ensure configuration files exist
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ expanded_path }}"
    owner: "{{ item.owner | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    mode: "{{ item.mode | default(omit) }}"
  loop: "{{ packages_config_files }}"
  loop_control:
    label: "{{ item.path }}"
  vars:
    expanded_path: "{{ item.path | expanduser }}"
    path_in_home_dir: "{{ (expanded_path | regex_findall('^/home/') | length) > 0 }}"
  become: "{{ item.become | default(not path_in_home_dir) }}"
