---
dotfiles_home: "~"

dotfiles_repo_url: https://github.com/flaudisio/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_update: true
dotfiles_repo_local_dest: "{{ dotfiles_home }}/.files"
dotfiles_repo_src_dir: src

dotfiles_extra_dirs: []

dotfiles_vim_plugins_dir: "{{ dotfiles_home }}/.vim/pack/plugins/start"

# dotfiles_vim_plugins:
#   - https://github.com/editorconfig/editorconfig-vim.git
#   - repo: https://github.com/preservim/nerdtree.git
#     version: 7.1.3
#     update_repo: false
dotfiles_vim_plugins: []
