---
# Ref: https://www.spotify.com/br-en/download/linux/

spotify_apt_repo_key_url: https://download.spotify.com/debian/pubkey_5384CE82BA52C83A.asc

spotify_apt_repo_key_file: /etc/apt/trusted.gpg.d/spotify.asc

spotify_apt_repo_line: deb https://repository.spotify.com stable non-free

spotify_apt_repo_file: spotify
