---
# Ref: https://brave.com/linux/

brave_apt_repo_name: brave-browser

brave_apt_repo_key_url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
brave_apt_repo_key_file: /usr/share/keyrings/brave-browser-archive-keyring.gpg

# Ref: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
brave_apt_repo_uri: https://brave-browser-apt-release.s3.brave.com
brave_apt_repo_suite: stable
brave_apt_repo_component: main
brave_apt_repo_architectures:
  - amd64
  - arm64
